### ISSUE TITLE
Broken links in README.adoc appearing on https://spring.io/guides/tutorials/react-and-spring-data-rest/

### ISSUE THREAD

**Issue by axiopisty** [spring-guides/tut-react-and-spring-data-rest#105]
There are several locations in the tutorial that state: *Unresolved directive in...*

For example I quote the very end of the tutorial:

> You made the webpage dynamic. But open another browser tab and point it at the same app. Changes in one tab won’t update anything in the other.
> 
> That is something we can address in the next section.
> 
> Unresolved directive in <stdin> - include::conditional/README.adoc[leveloffset=+1] Unresolved directive in <stdin> - include::events/README.adoc[leveloffset=+1] Unresolved directive in <stdin> - include::security/README.adoc[leveloffset=+1]

**Comment by mrsarm** [comment]
Yes, moreover, due to this error, **Part 3**, **Part 4** ... aren't accessible any more.

![Error Spring Guide](https://user-images.githubusercontent.com/1608415/59985195-7e090000-9606-11e9-96d3-665c032058ce.png)

**Comment by MiloBem** [comment]
fixed by #107

**Comment by gregturn** [comment]
Resolved via https://github.com/spring-guides/tut-react-and-spring-data-rest/commit/d957d773219f0809588031b64d4ce96c3e356bff.

**Comment by DavyGuedes** [comment]
Hi. This issue still persist.

![2019-09-18 (1)](https://user-images.githubusercontent.com/18080161/65185196-6abad480-da3d-11e9-9c8e-159c7e3b586b.png)
![2019-09-18](https://user-images.githubusercontent.com/18080161/65185197-6abad480-da3d-11e9-8eab-57bb80af8d1f.png)
